Accessible version
cant89/gianni-accordion-js pull request #1
Opened 2019-03-26 14:23 UTC by multivoltage

2019-03-26 22:32 UTC, cant89 requested changes
Ho fatto un po il Valerio della situa, abbi pazienza :D

2019-03-26 22:32 UTC, cant89 commented on README.md
> +  default is <code>selected</code>
"default is 0"

2019-03-26 22:32 UTC, cant89 commented on README.md
> +https://codepen.io/cant89/full/RLEoyV/ (original version)
cancella pure la mia, non serve averne due. Tanto l'accessibilità fa bene a chi la vuole e non ha side effects per chi non se ne cura

2019-03-26 22:32 UTC, cant89 commented on README.md
> +  // selectedClass: 'my-custom-open-class' -> by default is 'open'
default is 'selected' (se non erro)

2019-03-26 22:32 UTC, cant89 commented on README.md
> +/** if you want to hide show body for screenreader **/
Togli commento, tanto chi se ne fotte dell'accessibilità non ha side effects ad usare questa regola.

2019-03-26 22:32 UTC, cant89 commented on src/script.js
>              this.fire("elementOpened", el);
il fire dell'evento direi che è meglio metterlo dopo tutto...Mi aspetto che on("elementOpened") anche tutte le classi e gli attributi siano al loro posto

2019-03-26 22:32 UTC, cant89 commented on src/script.js
> +        el.content.setAttribute('aria-hidden', 'true');
I due aria vengono ripetuti uguali in un'altra parte, così come i loro opposti (true e false). Possiamo centralizzare con due metodi setCollapsedAria() e setExpandedAria()

2019-03-26 22:32 UTC, cant89 commented on src/script.js
> +          element.wrapper.classList.add(this.selectedClass)
nell'else non si può chiamare direttamente this.open(element)? fa già tutta sta roba qua

2019-03-26 22:32 UTC, cant89 commented on src/script.js
> +    setLandinData(el) {
setQualcosa**Data** è usato per settare dati (variabili), non per modificare il dom. 
Chiamalo collapseAtLanding e aggiungici anche 
_element.content.style.height = this.collapsedHeight_
che attualmente è nel constructor subito prima della chiamata a questa funzione

2019-03-26 22:32 UTC, cant89 commented on src/script.js
> +      this.openAtLandingIndex = -1
figo questo, ma non ho capito come usarlo. Dovrei passare l'indice dell'elemento che voglio avere aperto?

2019-03-27 14:00 UTC, multivoltage commented
> Ho fatto un po il Valerio della situa, abbi pazienza :D

Si....

2019-03-27 18:37 UTC, merged